---
apiVersion: v1
kind: Pod
metadata:
  name: utils
  labels:
    app: {{ template "blockchain-network.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  restartPolicy: "Never"
  volumes:
  - name: {{ template "blockchain-shared-pvc.name" . }}
    persistentVolumeClaim:
     claimName: {{ template "blockchain-shared-pvc.name" . }}
  - name: dockersocket
    hostPath:
      path: /var/run/docker.sock
  containers:
  - name: cryptogen
    image: {{ .Values.blockchain.toolsImage }}
    imagePullPolicy: {{ .Values.blockchain.pullPolicy }}
    command:
        - sh
        - -c
        - |
          while [ ! -f /shared/config/crypto-config.yaml ]; do
            echo Waiting for config files
            sleep 1
          done

          cryptogen generate --config /shared/config/crypto-config.yaml &&
          cp -r crypto-config /shared/

          for file in $(find /shared/ -iname *_sk); do
            dir=$(dirname $file); mv ${dir}/*_sk ${dir}/key.pem
          done

          find /shared -type d | xargs chmod a+rx &&
          find /shared -type f | xargs chmod a+r &&
          touch /shared/status_cryptogen_complete
    volumeMounts:
    - mountPath: /shared
      name: {{ template "blockchain-shared-pvc.name" . }}
  - name: configtxgen
    image: {{ .Values.blockchain.toolsImage }}
    imagePullPolicy: {{ .Values.blockchain.pullPolicy }}
    command:
      - sh
      - -c
      - |
        sleep 1

        while [ ! -f /shared/status_cryptogen_complete ]; do
          echo Waiting for cryptogen
          sleep 1
        done

        cp /shared/config/configtx.yaml /shared/configtx.yaml &&
        cd /shared/ &&
        configtxgen -profile TwoOrgsOrdererGenesis -outputBlock orderer.block &&
        find /shared -type d | xargs chmod a+rx &&
        find /shared -type f | xargs chmod a+r &&
        touch /shared/status_configtxgen_complete &&
        rm -f /shared/status_cryptogen_complete
    env:
     - name: PEERHOST1
       value: {{ template "blockchain-network.name" . }}-org1peer1
     - name: PEERPORT1
       value: "5010"
     - name: PEERHOST2
       value: {{ template "blockchain-network.name" . }}-org2peer1
     - name: PEERPORT2
       value: "5010"
     - name: ORDERER_URL
       value: {{ template "blockchain-network.name" . }}-orderer:31010
     - name: FABRIC_CFG_PATH
       value: /shared
    # - name: GODEBUG
    #   value: "netdns=go"
    volumeMounts:
    - mountPath: /shared
      name: {{ template "blockchain-shared-pvc.name" . }}
  - name: bootstrap
    image: {{ .Values.blockchain.toolsImage }}
    imagePullPolicy: {{ .Values.blockchain.pullPolicy }}
    command:
      - sh
      - -c
      - |
        sleep 1
        echo "Starting bootstrap"

        while [ ! -f /shared/status_configtxgen_complete ]; do
          echo Waiting for configtxgen
          sleep 1
        done

        echo \"Starting bootstrap\" &&
        cp -r /shared/config/cas /shared &&
        echo \"Done copying\" &&
        touch /shared/bootstrapped &&
        rm -f /shared/status_configtxgen_complete &&
        echo 'Done with bootstrapping'
    volumeMounts:
    - mountPath: /shared
      name: {{ template "blockchain-shared-pvc.name" . }}

