---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "blockchain.name" . }}-org1peer1
  labels:
    name: {{ template "blockchain.name" . }}-org1peer1
    app: {{ template "blockchain.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    run: {{ template "blockchain.name" . }}-org1peer1
spec:
  type: NodePort
  selector:
    name: {{ template "blockchain.name" . }}-org1peer1
    app: {{ template "blockchain.name" . }}
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    nodePort: 30110
    targetPort: 30110
    port: 30110
    name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "blockchain.name" . }}-couchdb1
  labels:
    app: {{ template "blockchain.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    run: {{ template "blockchain.name" . }}-couchdb1
spec:
  type: NodePort
  selector:
    name: {{ template "blockchain.name" . }}-couchdb1
    app: {{ template "blockchain.name" . }}
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 30984
    targetPort: 5984
    nodePort: 30984
    name: couchdb1