---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "blockchain.name" . }}-org1peer1
  labels:
    name: {{ template "blockchain.name" . }}-org1peer1
    app: {{ template "blockchain.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      name: {{ template "blockchain.name" . }}-org1peer1
      labels:
        app: {{ template "blockchain.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        name: {{ template "blockchain.name" . }}-org1peer1
    spec:
      volumes:
      - name: {{ template "blockchain-shared-pvc.name" . }}
        persistentVolumeClaim:
         claimName: {{ template "blockchain-shared-pvc.name" . }}
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock
      containers:
      - name: org1peer1
        image: {{ .Values.blockchain.peerImage }}
        imagePullPolicy: {{ .Values.blockchain.pullPolicy }}
        command:
          - sh
          - -c
          - |
            sleep 1

            while [ ! -f /shared/bootstrapped ]; do
              echo Waiting for bootstrap
              sleep 1
            done

            touch /shared/status_org1peer1_complete &&
            peer node start
        env:
        - name: FABRIC_LOGGING_SPEC
          value: INFO
        - name: CORE_CHAINCODE_LOGGING_SHIM
          value: INFO
        - name: CORE_CHAINCODE_LOGGING_LEVEL
          value: INFO
        - name: CORE_PEER_ADDRESSAUTODETECT
          value: "true"
        # - name: CORE_PEER_NETWORKID
        #   value: nid1
        - name: CORE_PEER_ID
          value: {{ template "blockchain.name" . }}-org1peer1
        - name: CORE_PEER_LISTENADDRESS
          value: 0.0.0.0:30110
        - name: CORE_PEER_ADDRESS
          value: {{ template "blockchain.name" . }}-org1peer1:30110
        # - name: CORE_PEER_CHAINCODEADDRESS
        #   value: {{ template "blockchain.name" . }}-org1peer1:7052
        - name: CORE_PEER_CHAINCODELISTENADDRESS
          value: 0.0.0.0:7052
        - name: CORE_PEER_COMMITTER_ENABLED
          value: "true"
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        - name: CORE_PEER_DISCOVERY_PERIOD
          value: 60s
        - name: CORE_PEER_DISCOVERY_TOUCHPERIOD
          value: 60s
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE
          value: "bridge"
        - name: CORE_VM_DOCKER_ATTACHSTDOUT
          value: "true"
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /shared/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
        - name: CORE_PEER_TLS_ENABLED
          value: "false"
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: CouchDB
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: {{ template "blockchain.name" . }}-couchdb1:30984
        - name: PEER_CFG_PATH
          value: peer_config/
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric/
        - name: ORDERER_URL
          value: {{ template "blockchain.name" . }}-orderer:31010
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
        - mountPath: /shared
          name: {{ template "blockchain-shared-pvc.name" . }}
        - mountPath: /host/var/run/docker.sock
          name: dockersocket
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "blockchain.name" . }}-couchdb1
  app: {{ template "blockchain.name" . }}
  chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  release: {{ .Release.Name }}
  heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ template "blockchain.name" . }}-couchdb1
        app: {{ template "blockchain.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - name: couchdb1
        image: {{ .Values.blockchain.couchdbImage }}
        imagePullPolicy: {{ .Values.blockchain.pullPolicy }}
        env:
        - name: DB_URL
          value: http://localhost:5984/member_db