---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "blockchain.name" . }}-ca
  labels:
    app: {{ template "blockchain.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    run: {{ template "blockchain.name" . }}-ca
spec:
  type: NodePort
  selector:
    name: {{ template "blockchain.name" . }}-ca
    app: {{ template "blockchain.name" . }}
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 7054
    nodePort: 30000
    name: grpc
