name: blockchain
version: 1.4.1
appVersion: 1.4.1
description: Hyperledger Fabric Chart
keywords:
  - blockchain
home: https://ibm-blockchain.github.io
sources:
  - https://github.ibm.com/czar0/fabric-on-kubernetes
maintainers:
  - name: mrshah-at-ibm
    email: mrshah@us.ibm.com
  - name: dhyey20
    email: dbshah@us.ibm.com
  - name: eddie-at-ibm
    email: deallen@us.ibm.com
engine: gotpl
icon: https://www.ibm.com/blogs/bluemix/wp-content/uploads/2016/02/IBM_Blockchain_Hero.png
