---
apiVersion: v1
kind: Pod
metadata:
  name: prep
spec:
  restartPolicy: "Never"
  volumes:
  - name: {{ template "ibm-blockchain-shared-pvc.name" . }}
    persistentVolumeClaim:
      claimName: {{ template "ibm-blockchain-shared-pvc.name" . }}
  - name: dockersocket
    hostPath:
      path: /var/run/docker.sock
  containers:
  - name: bootstrap
    image: {{ .Values.blockchain.toolsImage }}
    imagePullPolicy: {{ .Values.blockchain.pullPolicy }}
    command: ["sh", "-c", "sleep 100000" ]
    volumeMounts:
    - mountPath: /shared
      name: {{ template "ibm-blockchain-shared-pvc.name" . }}
