apiVersion: v1
kind: Service
metadata:
  name: {{ include "hlf-ca.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 7054
    name: grpc
  selector:
    app: {{ include "hlf-ca.name" . }}
    release: {{ .Release.Name }}
